# Generated by Django 3.2.3 on 2021-05-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210525_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='time_created',
            field=models.TimeField(auto_now=True),
        ),
    ]
