# Generated by Django 3.2.3 on 2021-05-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210526_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='temp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
