# Generated by Django 3.2.3 on 2021-05-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_request_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='request',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='request',
            name='time_created',
        ),
    ]
