# Generated by Django 3.2.3 on 2021-05-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210526_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='time_created',
            field=models.TimeField(auto_now=True),
        ),
    ]
