# Generated by Django 3.2.3 on 2021-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
