# Generated by Django 3.2.3 on 2021-05-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
        ('store_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.medlist')),
                ('storeOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_owner.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='medicine',
            field=models.ManyToManyField(through='store_owner.Stocks', to='meds.MedList'),
        ),
    ]
