# Generated by Django 3.2.3 on 2021-05-25 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meds', '0001_initial'),
        ('store_owner', '0003_auto_20210525_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ShopOwner',
        ),
    ]
