# Generated by Django 3.2.3 on 2021-05-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
        ('store_owner', '0004_rename_profile_shopowner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
