# Generated by Django 3.2.3 on 2021-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0007_auto_20210527_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='Latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='Longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
