# Generated by Django 3.2.3 on 2021-05-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0009_auto_20210527_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='Longitude',
        ),
    ]
