# Generated by Django 3.2.3 on 2021-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0010_auto_20210527_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
