# Generated by Django 3.2.3 on 2021-05-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0011_auto_20210527_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopowner',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='shopowner',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
