# Generated by Django 3.2.3 on 2021-05-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0012_auto_20210528_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
