# Generated by Django 3.2.3 on 2021-05-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_owner', '0013_shopowner_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
